# Common configuration shared by all profiles
spring.application.name=Lockedin
spring.main.allow-circular-references=true
spring.main.allow-bean-definition-overriding=true

# Activate local profile by default (for development)
spring.profiles.active=prod




